In [2]:
import pandas as pd

traffic = pd.read_csv("https://data.wprdc.org/datastore/dump/6dfd4f8f-cbf5-4917-a5eb-fd07f4403167")
traffic.head/()

,_id,id,device_id,record_oid,count_start_date,count_end_date,average_daily_car_traffic,average_daily_bike_traffic,counter_number,counter_type,...,longitude,latitude,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone
0,1,1011743669,85,1.445865e+09,2019-04-18,2019-04-26,4949.0,NaN,6,StatTrak,...,-79.967772,40.455733,Polish Hill,7.0,6.0,42003060500,6.0,6.0,2.0,2-6
1,2,1026101993,140,1.121444e+09,2019-01-24,NaN,NaN,NaN,NaN,Intersection Study,...,-79.952249,40.466157,Central Lawrenceville,7.0,9.0,42003090200,2.0,9.0,2.0,3-6
2,3,1032382575,11,1.539893e+09,2018-08-28,2018-09-04,NaN,NaN,NaN,NaN,...,-80.076469,40.460717,Windgap,2.0,28.0,42003563000,5.0,28.0,6.0,1-16
3,4,103627606,9,7.341951e+08,2018-07-17,2018-08-01,2741.0,NaN,NaN,StatTrak,...,-79.914335,40.437379,Squirrel Hill South,5.0,14.0,42003140800,3.0,14.0,4.0,2-18
4,5,1039546167,144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-80.019211,40.490794,Perry North,1.0,26.0,42003260200,1.0,26.0,1.0,1-15

In [4]:
traffic[['neighborhood', 'average_daily_car_traffic']].dropna().head(10)

           neighborhood  average_daily_car_traffic
0           Polish Hill                     4949.0
3   Squirrel Hill South                     2741.0
5     Central Northside                     1046.0
7           Polish Hill                     3015.0
10  Squirrel Hill South                     5592.0
13                Bluff                     1455.0
14      Crafton Heights                    11500.0
15            Shadyside                     6793.0
17        Highland Park                     7688.0
18          North Shore                    10350.0

In [5]:
traffic.groupby('neighborhood')['average_daily_car_traffic'].mean().sort_values().head(10)

neighborhood
South Side Flats             115.000000
Lincoln Place                126.000000
Lincoln-Lemington-Belmar     195.000000
Fineview                     419.000000
Allegheny West               477.000000
New Homestead                666.000000
Overbrook                    777.000000
Summer Hill                  937.000000
Upper Hill                   953.333333
Central Northside           1189.000000
Name: average_daily_car_traffic, dtype: float64

I used the city traffic dataset and focused on average daily car traffic by neighborhood. Then I compared the average traffic values across neighborhoods. Lower traffic may suggest a quieter neighborhood.

In [ ]:
traffic_by_neighborhood = traffic.groupby('neighborhood')['average_daily_car_traffic'].mean().sort_values().head(10)

traffic_by_neighborhood.plot(kind='barh', figsize=(10,6), title='Lowest Average Daily Car Traffic by Neighborhood')